### ISSUE TITLE
Ability to add Hashtag to a List

### ISSUE THREAD

**Issue by jtomchak** [jtomchak/mastodon#1]
## What
You can follow hashtags, and you can add people you follow to a list. Can I put a followed hashtag in a list? 
I’d like to follow, say #MLS during matches. But I don’t really want it in my timeline mixed up with everything else. And I selectively I don’t want to see it when there’s not a live match. 
(_note the first version of this will not make hashtags exclusive to a list, that would be considered an separate feature request_)

## Tasks
- [x] Fork and get local dev setup for Mastodon development
- [ ] Add tags :id as a method to Lists
- [ ] Lists will now be pulling from 2 resources. Accounts & Tags. 
- [ ] Replace personal instance repo with forked repo

## Resources
* [Ability to add hashtags to lists #7692](https://github.com/mastodon/mastodon/issues/7692)
* [Add hashtag to list #20715](https://github.com/mastodon/mastodon/issues/20715)

## Deliverables
* Able to via the API add not just add account id to a list, but another method

[Currently adding an account to a list](https://docs.joinmastodon.org/methods/lists/#accounts-add)
`POST /api/v1/lists/:id/accounts HTTP/1.1`

[Proposed adding a hashtag to a list](https://docs.joinmastodon.org/methods/tags/#follow)
`POST /api/v1/lists/:id/tags HTTP/1.1`
Add hashtags to the given list. Note that the user must be following this hashtag.

Returns: empty object
OAuth: User token + write:lists

* Deploy to personal Instance at cogwheel.social
* Ideally my "MLS" list that has no accounts added to it will populate and show posts w/ the #MLS hashtag rather than be empty. 
`GET /api/v1/timelines/list/:list_id HTTP/1.1`
[Timeline List API](https://docs.joinmastodon.org/methods/timelines/#list)
<img width="347" alt="Safari 2023-03-06 at 15 34 57@2x" src="https://user-images.githubusercontent.com/76360/223265768-64202b78-26bb-4f7c-bd6f-9d44bbd321b1.png">

More like this, but always available from the my list
<img width="340" alt="Safari 2023-03-06 at 15 36 59@2x" src="https://user-images.githubusercontent.com/76360/223266286-6390dfb0-9630-4da3-8ce6-a2f7056664d1.png">

### Motivation

This is a something I feel would be useful in helping organize, share, and ultimately make finding interesting content for the user easier.

**Comment by jtomchak** [comment]
Up and running: 

* Create the API route `POST /api/v1/lists/:id/tags HTTP/1.1` and mirror the logic from lists/accounts
* `RAILS_ENV=development bin/rails generate model ListTag list:belongs_to tag:belongs_to follow:belongs_to`
* Generate model and migration like list_account, but it won't be an account_id but rather a tag string

**Comment by jtomchak** [comment]
Created a Postman collection to make feedback loop faster

<img width="1774" alt="Postman 2023-03-15 at 09 38 54@2x" src="https://user-images.githubusercontent.com/76360/225379104-c3c3bc0b-2c65-4563-a5b4-4f78399c680f.png">

[![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/49655-fb661f00-794b-4d64-ade1-2b78d07e003a?action=collection%2Ffork&collection-url=entityId%3D49655-fb661f00-794b-4d64-ade1-2b78d07e003a%26entityType%3Dcollection%26workspaceId%3Ddda6a98d-4f8a-40ec-a5f4-082df0e52b82)
